# Generated by Django 2.2.6 on 2020-03-13 11:45

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('tid', models.IntegerField()),
                ('pubdate', models.IntegerField()),
                ('aid', models.IntegerField()),
                ('tags', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('duration', models.IntegerField()),
                ('stat_view', models.IntegerField()),
                ('stat_danmaku', models.IntegerField()),
                ('stat_reply', models.IntegerField()),
                ('stat_favorite', models.IntegerField()),
                ('stat_coin', models.IntegerField()),
                ('stat_share', models.IntegerField()),
                ('stat_like', models.IntegerField()),
                ('stat_dislike', models.IntegerField()),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('tid', models.IntegerField()),
                ('pubdate', models.IntegerField()),
                ('tag_id', models.BinaryField(max_length=12)),
                ('aids', djongo.models.fields.ArrayField(model_container=api.models.AidCollection)),
            ],
            options={
                'db_table': 'video_tag',
            },
        ),
        migrations.AddIndex(
            model_name='videotag',
            index=models.Index(fields=['_id'], name='video_tag__id_44bdbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='videotag',
            constraint=models.UniqueConstraint(fields=('tid', 'pubdate', 'tag_id'), name='unique_tid_pubdate_tagid'),
        ),
        migrations.AddIndex(
            model_name='videos',
            index=models.Index(fields=['tid', 'pubdate'], name='videos_tid_aae6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='videos',
            index=models.Index(fields=['_id'], name='videos__id_796a14_idx'),
        ),
        migrations.AddConstraint(
            model_name='videos',
            constraint=models.UniqueConstraint(fields=('aid',), name='unique_aid'),
        ),
        migrations.AddIndex(
            model_name='tags',
            index=models.Index(fields=['_id'], name='tags__id_fcf8f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='tags',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
