# Generated by Django 2.2.6 on 2019-10-25 09:31

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('aid', models.IntegerField()),
                ('tid', models.IntegerField()),
                ('title', models.CharField(max_length=128)),
                ('duration', models.IntegerField()),
                ('pubdate', models.IntegerField()),
                ('tags', models.CharField(max_length=128)),
                ('updated_at', models.IntegerField()),
                ('stat_view', models.IntegerField()),
                ('stat_danmaku', models.IntegerField()),
                ('stat_reply', models.IntegerField()),
                ('stat_favorite', models.IntegerField()),
                ('stat_coin', models.IntegerField()),
                ('stat_share', models.IntegerField()),
                ('stat_like', models.IntegerField()),
                ('stat_dislike', models.IntegerField()),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.AddIndex(
            model_name='videos',
            index=models.Index(fields=['tid', 'pubdate'], name='videos_tid_aae6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='videos',
            index=models.Index(fields=['aid'], name='videos_aid_e50ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='videos',
            index=models.Index(fields=['_id'], name='videos__id_796a14_idx'),
        ),
    ]
