# Generated by Django 2.2.11 on 2020-04-13 09:00

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('tid', models.IntegerField()),
                ('pubdate', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'records',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=36)),
                ('task_type', models.IntegerField()),
                ('tid', models.IntegerField()),
                ('time_from', models.IntegerField()),
                ('time_to', models.IntegerField()),
                ('time_start', models.IntegerField()),
                ('time_end', models.IntegerField()),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('tid', models.IntegerField()),
                ('pubdate', models.IntegerField()),
                ('aid', models.IntegerField()),
                ('tags', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('duration', models.IntegerField()),
                ('stat_view', models.IntegerField()),
                ('stat_danmaku', models.IntegerField()),
                ('stat_reply', models.IntegerField()),
                ('stat_favorite', models.IntegerField()),
                ('stat_coin', models.IntegerField()),
                ('stat_share', models.IntegerField()),
                ('stat_like', models.IntegerField()),
                ('stat_dislike', models.IntegerField()),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('tid', models.IntegerField()),
                ('pubdate', models.IntegerField()),
                ('tag_id', models.BinaryField(max_length=12)),
                ('aids', djongo.models.fields.ListField(verbose_name=models.IntegerField())),
                ('avg_stat_view', models.IntegerField()),
                ('avg_stat_danmaku', models.IntegerField()),
                ('avg_stat_reply', models.IntegerField()),
                ('avg_stat_favorite', models.IntegerField()),
                ('avg_stat_coin', models.IntegerField()),
                ('avg_stat_share', models.IntegerField()),
                ('avg_stat_like', models.IntegerField()),
                ('avg_stat_dislike', models.IntegerField()),
            ],
            options={
                'db_table': 'video_tag',
            },
        ),
        migrations.AddIndex(
            model_name='videotag',
            index=models.Index(fields=['_id'], name='video_tag__id_44bdbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='videotag',
            constraint=models.UniqueConstraint(fields=('tid', 'pubdate', 'tag_id'), name='unique_tid_pubdate_tagid'),
        ),
        migrations.AddIndex(
            model_name='videos',
            index=models.Index(fields=['tid', 'pubdate'], name='videos_tid_aae6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='videos',
            index=models.Index(fields=['_id'], name='videos__id_796a14_idx'),
        ),
        migrations.AddConstraint(
            model_name='videos',
            constraint=models.UniqueConstraint(fields=('aid',), name='unique_aid'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['_id'], name='tasks__id_2ef6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['time_start'], name='tasks_time_st_67a55d_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasks',
            constraint=models.UniqueConstraint(fields=('task_id',), name='unique_task_id'),
        ),
        migrations.AddIndex(
            model_name='tags',
            index=models.Index(fields=['_id'], name='tags__id_fcf8f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='tags',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
        migrations.AddIndex(
            model_name='records',
            index=models.Index(fields=['_id'], name='records__id_26c711_idx'),
        ),
        migrations.AddConstraint(
            model_name='records',
            constraint=models.UniqueConstraint(fields=('tid', 'pubdate'), name='unique_tid_pubdate'),
        ),
    ]
