# Generated by Django 2.2.6 on 2020-03-17 02:04

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('tid', models.IntegerField()),
                ('pubdate', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'records',
            },
        ),
        migrations.AddField(
            model_name='videotag',
            name='avg_stat_view',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='videotag',
            name='avg_stat_danmaku',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='videotag',
            name='avg_stat_reply',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='videotag',
            name='avg_stat_favorite',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='videotag',
            name='avg_stat_coin',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='videotag',
            name='avg_stat_share',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='videotag',
            name='avg_stat_like',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='videotag',
            name='avg_stat_dislike',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='records',
            index=models.Index(fields=['_id'], name='records__id_26c711_idx'),
        ),
        migrations.AddConstraint(
            model_name='records',
            constraint=models.UniqueConstraint(fields=('tid', 'pubdate'), name='unique_tid_pubdate'),
        ),
    ]
