# Generated by Django 2.2.11 on 2020-04-04 02:25

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200317_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=36)),
                ('task_type', models.IntegerField()),
                ('tid', models.IntegerField()),
                ('time_from', models.IntegerField()),
                ('time_to', models.IntegerField()),
                ('time_start', models.IntegerField()),
                ('time_end', models.IntegerField()),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['_id'], name='tasks__id_2ef6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['time_start'], name='tasks__time_start_5fe24d_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasks',
            constraint=models.UniqueConstraint(fields=('task_id',), name='unique_task_id'),
        ),
    ]
